name: Dissect CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: fox-it/dissect-workflow-templates/.github/workflows/dissect-ci-template.yml@update-build-native
    secrets: inherit
    with:
      build-native: true
      run-benchmarks: true

  publish:
    if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
    needs: [ci]
    runs-on: ubuntu-latest
    environment: dissect_publish
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: packages*
          path: dist/
          merge-multiple: true
      # According to the documentation, it automatically looks inside the `dist/` folder for packages.
      - name: Publish package distributions to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1

  trigger-tests:
    needs: [publish]
    uses: fox-it/dissect-workflow-templates/.github/workflows/dissect-ci-demand-test-template.yml@main
    secrets: inherit
    with:
      on-demand-test: 'dissect.target'
